### PR TITLE
js: Fix context usage with sub.Fetch

### LINKED ISSUE #834: Fetch ignores context timeout.
nats.go version: **1.13.3**
nats version: **2.6.1**

I have examined at the Fetch code in `js.go` and I think there may be some issues with the logic:

When a context is passed in that has a context timeout, and no explicit `PullOpts` timeout, the code sets the internal `ttl` to the default timeout value.  It uses this default value `ttl` to time out the request returning `context.DeadlineExceeded` thereby ignoring the context timeout value.

When a timeout value is provided through `PullOpts` without a context, the timeout value is respected.

The check at the start of the function prevents supplying both, so therefore it is therefore impossible to provide a cancellable context to Fetch, and and also a timeout.

Providing no timeout value is causing Fetch to stall for us, but I also need to be able to cancel the context during a graceful shutdown of the server.

### PR DESCRIPTION
**Pull request by wallyqs**
The deadline of a context is now used to calculate the time used for `expires` instead of the default `ttl` of the JetStream context which was `5s` by default.  This was preventing library users from passing a context with a custom timeout.

This also disallows the usage of `context.Background` to make it explicit that `sub.Fetch` has to be used with a context that has a timeout since each fetch request has to include an expire time anyway.

In case `context.WithCancel` is used, then a child context with the same duration as the JetStream context default timeout will be created. 

It is also updated to prevent using both timeout and context options with `msg.InProgress()`, `msg.AckSync()`.

Fixes #834 #833 

Signed-off-by: Waldemar Quevedo <wally@synadia.com>

### CODE REVIEW

File: js.go [hunk 1]
```diff
@@ -2166,6 +2168,19 @@ func (sub *Subscription) Fetch(batch int, opts ...PullOpt) ([]*Msg, error) {
 		defer cancel()
 	}
 
+	deadline, hasDeadline := ctx.Deadline()
```
Comment (kozlovic) [inline js.go:2171]: Few lines above, we set `ctx = o.ctx`, which means we use what is set in the option. Then we say `if o.ctx == nil` we create a context with timeout. So I feel like we should, to make it clear, check `if ctx == nil` (instead of o.ctx) and then have a `else` where we check for "hasDeadline" in the user provided context.


The `deadline` can then be gotten down below, before the `ttl = time.Until(deadline)`

File: js.go [hunk 2]
```diff
@@ -2166,6 +2168,19 @@ func (sub *Subscription) Fetch(batch int, opts ...PullOpt) ([]*Msg, error) {
...
+	if !hasDeadline {
+		// Prevent from passing the background context which will just block
+		// and cannot be canceled either.
+		if octx, ok := ctx.(ContextOpt); ok && octx.Context == context.Background() {
+			return nil, ErrNoDeadlineContext
+		}
+		// If the context did not have a deadline, then create a new child context
+		// that will use the default timeout from the JS context.
+		ctx, cancel = context.WithTimeout(ctx, ttl)
```
Comment (kozlovic) [inline js.go:2180]: Do we need to create a context with timeout from the user-given context here? If not, then code could be even more refactored to check for `ctx = o.ctx` being not nil first, just to check for "has deadline" and if so set ctx to nil so there is then the check for `nil` and creation with background() context. If we need to use the user-given context, then ok with this code.

**Review by kozlovic — CHANGES_REQUESTED** [review]
Would recommend a little bit of refactor and more depending on answer to question regarding user-given context without deadline.

File: js.go (hunk 2 above)
Comment (wallyqs) [reply js.go:2178]: Yes we need to chain the context from the parent one so that if it is canceled then the child one is canceled as well.

**Review by kozlovic — APPROVED** [review]
LGTM
